### PR TITLE
fix(input): input display with hidden type

### LINKED ISSUE #3170: [BUG] - <Input type='hidden' /> does not hide the entire component
### NextUI Version

2.4.0

### Describe the bug

Adding the `type='hidden'` attribute on the `Input` component does not hide it completely - it only hides the underlying HTML `<input>`. 

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

`<Input type='hidden' />`

### Expected behavior

Ideally the entire element should be hidden while still being able to retrieve the value in a form submission, etc.

### Screenshots or Videos

The wrapper still being visible:
image

### Operating System Version

Windows

### Browser

Edge

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #3170

## 📝 Description

- handle the display of the input for hidden type

## ⛳️ Current behavior (updates)

a readonly input is shown

## 🚀 New behavior

input is not shown if `type` is `hidden`

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved an issue where `Input` components with a hidden type were incorrectly displayed.

- **Tests**
  - Added a new test case to verify the correct visibility behavior of `Input` components with a hidden type.

- **Refactor**
  - Updated base CSS classes for `Input` components to conditionally include a hidden class based on data attributes.

### CODE REVIEW

File: packages/components/input/src/use-input.ts [hunk 1]
```diff
@@ -288,6 +292,7 @@ export function useInput<T extends HTMLInputElement | HTMLTextAreaElement = HTML
         "data-has-value": dataAttr(!isPlaceholderShown),
         ...focusWithinProps,
         ...props,
+        hidden: isHiddenType,
```
Comment (jrgarciadev) [inline packages/components/input/src/use-input.ts:295]:
```suggestion
        "data-hidden": dataAttr(isHiddenType),
```

File: packages/components/input/src/use-input.ts [hunk 2]
```diff
@@ -145,9 +145,13 @@ export function useInput<T extends HTMLInputElement | HTMLTextAreaElement = HTML
   const isFilledByDefault = ["date", "time", "month", "week", "range"].includes(type!);
   const isFilled = !isEmpty(inputValue) || isFilledByDefault;
   const isFilledWithin = isFilled || isFocusWithin;
-  const baseStyles = clsx(classNames?.base, className, isFilled ? "is-filled" : "");
+  const isHiddenType = type === "hidden";
   const isMultiline = originalProps.isMultiline;
 
+  const baseStyles = clsx(classNames?.base, className, isFilled ? "is-filled" : "", {
+    hidden: isHiddenType,
```
Comment (jrgarciadev) [inline packages/components/input/src/use-input.ts:152]: Move this to the input styles in the `theme` package, use the `data-hidden` attr

Comment (jrgarciadev) [reply packages/components/input/src/use-input.ts:152]: The reason is because tailwindcss only compiles the styles inside the `theme` package not inside the `react` or `input` one

File: packages/core/theme/src/components/input.ts [hunk 3]
```diff
@@ -236,6 +236,11 @@ const input = tv({
         clearButton: ["transition-opacity", "motion-reduce:transition-none"],
       },
     },
+    isHiddenType: {
+      true: {
+        base: "hidden",
+      },
+    },
```
Comment (jrgarciadev) [inline packages/core/theme/src/components/input.ts:243]: @wingkwong adding this as a variant means that the Input component will receive `isHiddenType` as prop, instead of adding a variant, please use the `data-hidden` prop.

e.g.

`base: "data-[hidden=true]:hidden"`

**Review by jrgarciadev — APPROVED** [review]
