### PR TITLE
fix(checkbox): incorrect onChange typing in Checkbox Group

### LINKED ISSUE #2594: [BUG] Checkbox group onchange incorrect type
### NextUI Version

2.2.10

### Describe the bug

I'm trying to create a `CheckboxGroup` with `onChange` event, but cannot really get the type correct. 
For example, if I try to do `const handleOnChange = (values: string[]) => {}` then TypeScript will complain the following. 

```
Type '(values: string[]) => void' is not assignable to type 'FormEventHandler<HTMLDivElement> & ((value: string[]) => void)'.
  Type '(values: string[]) => void' is not assignable to type 'FormEventHandler<HTMLDivElement>'.
    Types of parameters 'values' and 'event' are incompatible.
      Type 'FormEvent<HTMLDivElement>' is missing the following properties from type 'string[]': length, pop, push, concat, and 35 more.ts(2322)
```

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-eft3qw?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

See the stackblitz URL. 

### Expected behavior

No type error according to documentation: https://nextui.org/docs/components/checkbox-group#checkbox-group-events

### Screenshots or Videos

image

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #2594

## 📝 Description

as titled

## ⛳️ Current behavior (updates)

image

## 🚀 New behavior

image

## Summary by CodeRabbit

- **Bug Fixes**
	- Fixed an issue with incorrect `onChange` typing in Checkbox Group, ensuring it now correctly handles an array of strings as values.

### CODE REVIEW

File: packages/components/checkbox/src/use-checkbox-group.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {clsx, safeAriaLabel} from "@nextui-org/shared-utils";
 
 import {CheckboxProps} from "./index";
 
-interface Props extends HTMLNextUIProps<"div"> {
+interface Props extends Omit<HTMLNextUIProps<"div">, "onChange"> {
```
Comment (ryo-manba) [inline packages/components/checkbox/src/use-checkbox-group.ts:17]: As indicated by the warning, the issue resides with `FormEventHandler<HTMLDivElement>`. Therefore, I believe the following code should be corrected.
https://github.com/nextui-org/nextui/blob/main/packages/components/checkbox/src/use-checkbox-group.ts#L49

I think it would suffice to simply remove `onChange` from `Props`.
```
export type UseCheckboxGroupProps = Omit<Props, "onChange"> &
```

This would eliminate the need to redefine `onChange`.

Comment (wingkwong) [reply packages/components/checkbox/src/use-checkbox-group.ts]: Thanks. much cleaner.

**Review by ryo-manba — APPROVED** [review]

**Review by jrgarciadev — APPROVED** [review]
