### PR TITLE
fix(select): import HiddenSelect and UseSelectProps

### LINKED ISSUE #3356: [BUG] - Import HiddenSelect and UseSelectProps for Select
### NextUI Version

2.4.1

### Describe the bug

I want to create my own `Select` based on the source code, but I was faced with the fact that it cannot be repeated. Missing `HiddenSelect` and `UseSelectProps` for import.

packages/components/select/src/select.tsx
```typescript
import {HiddenSelect} from "./hidden-select";
import {UseSelectProps, useSelect} from "./use-select";
***

 return (
    <div {...getBaseProps()}>
      <HiddenSelect {...getHiddenSelectProps()} /> 
***
``` 

My code:
```typescript
import { HiddenSelect, UseSelectProps } from '@nextui-org/react' // error
``` 

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Create your own select
2. Copy the code from the `packages/components/select/src/select.tsx`
3. Get an import error for `HiddenSelect` and `UseSelectProps`

### Expected behavior

`HiddenSelect` and `UseSelectProps` available for import

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ryo-manba**
Closes #3356 

## 📝 Description

Fixed import HiddenSelect and UseSelectProps for Select.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

No.

## Summary by CodeRabbit

- **New Features**
  - Expanded the public API of the select component to include `HiddenSelect`. This update improves the flexibility and customization options for developers using the select component.

### CODE REVIEW

File: packages/components/select/src/index.ts [hunk 1]
```diff
@@ -3,15 +3,18 @@ import type {ListboxItemProps, ListboxSectionProps} from "@nextui-org/listbox";
...
 
 import Select from "./select";
+import {HiddenSelect} from "./hidden-select";
 
 // export types
 export type {SelectProps} from "./select";
 export type {ListboxItemProps as SelectItemProps};
 export type {ListboxSectionProps as SelectSectionProps};
 export type {SelectedItemProps, SelectedItems} from "./use-select";
+export type {UseSelectProps} from "./use-select";
```
Comment (wingkwong) [inline packages/components/select/src/index.ts:13]: can merge with L12 since `UseSelectProps` is also from `./use-select`

File: packages/components/select/src/index.ts [hunk 2]
```diff
@@ -3,15 +3,18 @@ import type {ListboxItemProps, ListboxSectionProps} from "@nextui-org/listbox";
...
 
 // export hooks
 export {useSelect} from "./use-select";
 
 // export component
 export {Select, ListboxItem as SelectItem, ListboxSection as SelectSection};
+export {HiddenSelect};
```
Comment (wingkwong) [inline packages/components/select/src/index.ts:20]: merge with L19

**Comment by rettimo** [comment]
Thank you very much for the quick response ❤️. When can I expect a solution to this problem? My company needs these updates ASAP.

**Review by rettimo — APPROVED** [review]

**Review by wingkwong — APPROVED** [review]

**Review by jrgarciadev — APPROVED** [review]
