### PR TITLE
fix(popover): correct position logic

### LINKED ISSUE #4466: [BUG] - DropDown arrow position
### NextUI Version

2.6.10

### Describe the bug

Hi, I think that in the latest updates, the position of the arrow in the dropdown is bugged. Regardless of where I set the placement, the arrow ends up misplaced. I'm attaching a sandbox with the code and some images.

### Your Example Website or App

https://codesandbox.io/p/devbox/brave-david-l3j8xl?file=%2FApp.jsx%3A131%2C9 

### Steps to Reproduce the Bug or Issue

1. Set placement='bottom-end'
2. Open the dropdown

### Expected behavior

I was expecting behavior similar to a popover.
image
`placement='bottom-end'`

### Screenshots or Videos

image
image
image

### Operating System Version

Windows

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ryo-manba**
Closes #4466 

## 📝 Description

This PR fixes the initial position logic for the Popover.  
Previously, the popover could animate in the wrong direction or fail to show the DropDown arrow.  

## ⛳️ Current behavior (updates)

- The popover occasionally animates incorrectly.
- The DropDown arrow may fail to appear.

Autocomplete and Select animations are also incorrect.
- https://canary.nextui.org/docs/components/autocomplete
- https://canary.nextui.org/docs/components/select

## 🚀 New behavior

- Popover animates from the correct direction.
- The DropDown arrow displays properly.

https://github.com/user-attachments/assets/78415f0a-5d87-471b-98e2-87dbd5fc0d60

Arrow is now applied correctly. However, the arrow’s position is slightly off for `left-start` or `right-end` placements, which will be addressed separately:

See: https://github.com/nextui-org/nextui/blob/canary/packages/core/theme/src/components/popover.ts#L58-L61

https://github.com/user-attachments/assets/35db0d8a-cdb5-4c71-b4a5-5a1477a7d260

https://github.com/user-attachments/assets/56f7ebd8-5df7-4073-801a-a461cf8663c9

I also fixed the issue causing the Select and Autocomplete animation to be misaligned.

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information

Related PRs

- https://github.com/nextui-org/nextui/pull/4288
- https://github.com/nextui-org/nextui/pull/4460

## Summary by CodeRabbit

- **Bug Fixes**
	- Resolved placement and animation issues for dropdown, popover, and select components
	- Fixed initial popover animation and arrow display (related to issue #4466)

- **New Features**
	- Added new placement stories for dropdown, select, and autocomplete components
	- Enhanced component positioning flexibility

- **Refactor**
	- Simplified overlay positioning logic
	- Streamlined placement handling for various UI components

### CODE REVIEW

File: packages/components/popover/src/use-popover.ts [hunk 1]
```diff
@@ -174,6 +179,16 @@ export function usePopover(originalProps: UsePopoverProps) {
...
 
+  const placement = useMemo(() => {
+    // If ariaPlacement is null, popoverProps.style isn't set,
+    // so we return null to avoid an incorrect animation value.
+    if (!ariaPlacement) {
+      return null;
+    }
+
+    return getShouldUseAxisPlacement(ariaPlacement, placementProp) ? ariaPlacement : placementProp;
+  }, [ariaPlacement, placementProp]);
```
Comment (ryo-manba) [inline packages/components/popover/src/use-popover.ts:190]: Incorrect initial placement caused animation to be applied in the wrong direction.
