### PR TITLE
fix(components): isdisabled does not disable dropdown

### LINKED ISSUE #2276: [BUG] - `isDisabled` does not disabled dropdown
### NextUI Version

2.2.9

### Describe the bug

As described [in the docs](https://nextui.org/docs/components/dropdown#dropdown-props), adding an `isDisabled` prop and setting it to true does not disable a dropdown

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-xzrmx5?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Create a dropdown
2. Add `isDisabled` prop
3. Use the dropdown

### Expected behavior

the dropdown should be disabled

### Screenshots or Videos

_No response_

### Operating System Version

MacOS

### Browser

Firefox

### PR DESCRIPTION
**Pull request by kuri-sun**
Closes #2276

## 📝 Description

[Based on the docs](https://nextui.org/docs/components/dropdown#dropdown-props), adding an isDisabled prop and setting it to true does not disable a dropdown

## ⛳️ Current behavior (updates)

The `isDisabled` prop does not work, because the Dropdown component does not pass the `isDisabled` prop to the PopoverTrigger component.

## 🚀 New behavior

It disables the trigger when `isDisabled` prop gets passed.

https://github.com/nextui-org/nextui/assets/62743644/268482fe-6a70-461f-8981-81d8cd3f559f

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information

N/A

### CODE REVIEW

File: packages/components/dropdown/src/use-dropdown.ts [hunk 1]
```diff
@@ -119,15 +119,15 @@ export function useDropdown(props: UseDropdownProps) {
...
   const getMenuTriggerProps: PropGetter = (
-    props = {},
+    originalProps = {},
     _ref: Ref<any> | null | undefined = null,
   ) => {
     // These props are not needed for the menu trigger since it is handled by the popover trigger.
     // eslint-disable-next-line @typescript-eslint/no-unused-vars
     const {onKeyDown, onPress, onPressStart, ...otherMenuTriggerProps} = menuTriggerProps;
 
     return {
```
Comment (kuri-sun) [inline packages/components/dropdown/src/use-dropdown.ts:129]: It is important here to use `props.isDisabled` so that the PopoverTrigger component can respect another `isDisabled` gets passed by the user. (Otherwise, the unit test is going to fail.)

**Review by jrgarciadev — APPROVED** [review]
