### PR TITLE
fix(alert): propagate className

### LINKED ISSUE #4533: [BUG] - Alert seems not propagate className
### NextUI Version

2.6.11

### Describe the bug

When we add a `className` in the Alert component the className not appears in the DOM.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

```tsx
<Alert hideIcon color="primary" variant="faded" className="Random">
Some content
</Alert>
```

### Expected behavior

The "Random" class should appears in the DOM.

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #4533

## 📝 Description

Apply className to base (i.e. the same pattern like other components)

## ⛳️ Current behavior (updates)

`className` doesn't add to base

## 🚀 New behavior

`className` is added to base

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved class name handling for the Alert component
	- Enhanced styling flexibility for the `@nextui-org/alert` package
	- Resolved an issue related to class name propagation (Issue #4533)
- **New Features**
	- Added support for custom class names in the Alert component

### CODE REVIEW

File: packages/components/alert/src/use-alert.ts [hunk 1]
```diff
@@ -123,8 +124,11 @@ export function useAlert(originalProps: UseAlertProps) {
     onClose?.();
   }, [setIsVisible, onClose]);
 
+  const baseStyles = clsx(classNames?.base, className);
+
   const slots = useMemo(
-    () => alert({hasContent: !isEmpty(description) || !isEmpty(children), ...variantProps}),
+    () =>
+      alert({hasContent: !isEmpty(description) || !isEmpty(children), ...variantProps, className}),
```
Comment (ryo-manba) [inline packages/components/alert/src/use-alert.ts:131]: Isn't it unnecessary to provide a `className`?

**Review by ryo-manba — APPROVED** [review]
LGTM, thanks!
