### PR TITLE
fix: missing aria labels in date range picker

### LINKED ISSUE #2804: [BUG] - Date range picker gives aria label warning even when labelled
### NextUI Version

2.3.5

### Describe the bug

Using the date range picker (a great new addition!) causes lots of aria warnings.

Monosnap trippix 2024-04-19 09-04-23

### Your Example Website or App

```
<DateRangePicker
  key={index} // I'm looping over a bunch of planned date ranges
  label="Dates"
  value={{ start: plan.dates.start, end: plan.dates.end }}
  isRequired
/>
```

### Steps to Reproduce the Bug or Issue

1. Use the `DateRangePicker` (even with a `label`)

### Expected behavior

There shouldn't be any warnings, but there are. You can see them on the [`DateRangePicker` docs page](https://nextui.org/docs/components/date-range-picker).

### Screenshots or Videos

Monosnap trippix 2024-04-19 09-04-23

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ryo-manba**
Closes #2804

## 📝 Description

Fixed an issue where label properties were not being properly translated into aria labels within the DateRangePicker component, leading to accessibility warnings even when labels were provided.

### Test Steps
1. Open https://nextui.org/docs/components/date-range-picker and observe the following warning in devtools:
> If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility.

2. Open https://nextui-docs-v2-d0x6bna9p-nextui-org.vercel.app/docs/components/date-range-picker and verify that the warning is no longer present.

## ⛳️ Current behavior (updates)

Setting label props still triggers aria warnings.

## 🚀 New behavior

Setting label props no longer triggers aria warnings.

## 💣 Is this a breaking change (Yes/No):

No.

## Summary by CodeRabbit

- **Bug Fixes**
	- Fixed missing aria labels in the date range picker to enhance accessibility.

- **New Features**
	- Improved label handling in the date range picker for better clarity and usability.

- **Documentation**
	- Updated component documentation to reflect changes in label properties and accessibility improvements.

### CODE REVIEW

File: apps/docs/content/components/date-range-picker/time-zones.ts [hunk 1]
```diff
@@ -9,21 +9,23 @@ export default function App() {
...
         labelPlacement="outside"
       />
-  </div>
+    </div>
   );
 }`;
 
 const react = {
-  "/App.tsx": AppTs,
+  "/App.jsx": App,
```
Comment (ryo-manba) [inline apps/docs/content/components/date-range-picker/time-zones.ts:28]: The code example was not displayed correctly.
https://nextui.org/docs/components/date-range-picker#time-zones

image

Comment (wingkwong) [reply apps/docs/content/components/date-range-picker/time-zones.ts:28]: Have you tried removing `node_modules` and install again? This is what I see in your PR branch. Only JS one. No TS.

image

Comment (ryo-manba) [reply apps/docs/content/components/date-range-picker/time-zones.ts:28]: @wingkwong 
That is expected. No TypeScript examples are shown, as can be seen in the other examples. The code before my fixes unnecessarily displayed broken TypeScript examples.

**Review by wingkwong — APPROVED** [review]
