### PR TITLE
fix(input): added hover and focus to input when label placement is outside-left #2328

### LINKED ISSUE #2328: [BUG] - `outside-left` label does not focus input
### NextUI Version

2.2.9

### Describe the bug

When clicked on the label with `outside-left` placement, input doesn't get focus.

### Your Example Website or App

https://storybook.nextui.org/?path=/story/components-input--label-placement

### Steps to Reproduce the Bug or Issue

1. Open [official storybook page](https://storybook.nextui.org/?path=/story/components-input--label-placement) or [documentation page](https://nextui.org/docs/components/input#label-placements).
2. Click on "Email" label with `outside-left` placement.
3. Nothing happens.

Reproducible in Chrome, Safari and Firefox

### Expected behavior

I am expecting the same behaviour as clicking on `Email` label with `outside` placement with placeholder.

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ShrinidhiUpadhyaya**
Closes #2328

## 📝 Description
When clicked or hovered on the label with `outside-left` placement, input doesn't get focus and no hover effect.

## ⛳️ Current behavior (updates)

https://github.com/nextui-org/nextui/assets/8769408/f135464d-167a-4595-884f-f769670b92b3

## 🚀 New behavior

https://github.com/nextui-org/nextui/assets/8769408/13610199-072b-4e8d-a6b9-0f75a96c430a

## 📝 Additional Information

-   `const {isHovered, hoverProps} = useHover({isDisabled: !!originalProps?.isDisabled});` can also be renamed as    `const {isHovered: isInputHovered, hoverProps: inputHoverProps} = useHover({isDisabled: !!originalProps?.isDisabled});` so the hover variables can be easily identified for the input and the label.

- If the PR gets accepted please use my GitHub email-id (shrinidhiupadhyaya1195@gmail.com) instead of my other email-id for the Co-authored-by: message.

## Summary by CodeRabbit

- **Bug Fixes**
    - Improved hover and focus behaviors for input labels when placed outside-left.
    - Enhanced label interaction by enabling pointer events on them.

### CODE REVIEW

File: packages/components/input/src/use-input.ts [hunk 1]
```diff
@@ -299,11 +304,10 @@ export function useInput<T extends HTMLInputElement | HTMLTextAreaElement = HTML
       return {
         "data-slot": "label",
         className: slots.label({class: classNames?.label}),
-        ...labelProps,
-        ...props,
+        ...mergeProps(labelProps, props, labelHoverProps),
```
Comment (wingkwong) [inline packages/components/input/src/use-input.ts:307]: props should have the higher precedence to override previous props.

```ts
...mergeProps(labelProps, labelHoverProps, props),
```

**Review by wingkwong — APPROVED** [review]
