### PR TITLE
fix(popover): unexpected props on a DOM element

### LINKED ISSUE #2474: [BUG] - React does not recognize the `originalProps ``isDisabled` prop on a DOM element.
### NextUI Version

2.2.10

### Describe the bug

``` bash
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:15:43
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:11:35
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:16:11
    at Dropdown (file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:14:11)
```

--------

``` bash
Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:15:43
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:11:35
    at file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:16:11
    at Dropdown (file:///Users/saadfarooq/Developer/Per-Diem/pos-onboarding-dashboard/node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:14:11)

```

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

``` js
const Dropdown: FC<DropdownProps> = ({
  baseClass = "",
  triggerClass = "",
  backdropClass = "",
  arrowClass = "",
  useMenuIcon = true,
  isDisabled = false,
  disabledKeys,
  triggerColor = "#A098AE",
  menuTriggerClass = "h-6 w-6 cursor-pointer",
  triggerDataCy = "trigger_dropdown",
  customTrigger = <MdMoreHoriz size={22} color={triggerColor} />,
  children,
}) => {
  return (
    <NextDropdown
      classNames={{
        base: `${baseClass}`,
        trigger: `${triggerClass}`,
        backdrop: `${backdropClass}`,
        arrow: `${arrowClass}`,
      }}
      isDisabled={isDisabled}
    >
      <DropdownTrigger>
        {
          <div data-cy={triggerDataCy} className={menuTriggerClass}>
            {useMenuIcon ? (
              <MdMoreHoriz size={22} color={triggerColor} />
            ) : (
              customTrigger
            )}
          </div>
        }
      </DropdownTrigger>
      <DropdownMenu
        disabledKeys={disabledKeys}
        itemClasses={{
          base: [
            "data-[hover=true]:bg-[#F2F7FE]",
            "data-[selectable=true]:focus:bg-[#F2F7FE]",
            "data-[focus-visible=true]:ring-[#F2F7FE]",
          ],
        }}
      >
        {children}
      </DropdownMenu>
    </NextDropdown>
  );
};

export default Dropdown;

````

Now using this as component

``` js
   <Dropdown
            menuTriggerClass=""
            useMenuIcon={false}
            customTrigger={
              <div className="flex items-center gap-2 px-1 md:px-0">
                <Avatar
                  size="md"
                  name={`${String(user?.first_name?.[0] || "U")} ${String(
                    user?.last_name?.[0] || "",
                  )}`}
                  as="button"
                  classNames={{
                    name: "text-center font-medium text-black ",
                  }}
                  className="bg-[#FFC96B] transition-transform "
                />
                <h1 className="hidden md:block">{`${String(
                  user?.first_name || "User",
                )} ${String(user?.last_name || "")}  `}</h1>
              </div>
            }
          >
            <DropdownItem>
              <div>
                <p className="text-sm font-medium">{user?.email}</p>
                <p className="py-2 text-sm text-pd-gray-500">
                  {user?.type || ""}
                </p>
                {isEmployee(userObj) && (
                  <div className="block pb-3 md:hidden">
                    <Chip
                      size="sm"
                      color="default"
                      variant="dot"
                      className={`rounded-lg bg-[#E4E5E7] text-xs`}
                    >
                      View only mode
                    </Chip>
                  </div>
                )}
                <Divider />
              </div>
            </DropdownItem>
            {isAdmin ? (
              <DropdownItem onClick={() => switchStoreController.openModal()}>
                <h1>Switch account</h1>
              </DropdownItem>
            ) : (
              <DropdownItem className="hidden"></DropdownItem>
            )}
            <DropdownItem
              onClick={() => {
                logoutController.openModal();
              }}
            >
              <h1 className="font-medium text-[#D72C0D]">Logout</h1>
            </DropdownItem>
          </Dropdown>


```

### Expected behavior

Not to throw the error.

### Screenshots or Videos

image
image

### Operating System Version

macOS

### Browser

Chrome

### LINKED ISSUE #2528: [BUG] - Warning: React does not recognize the `originalProps` prop on a DOM element.
### NextUI Version

2.2.10

### Describe the bug

On running the app locally this warning is displayed:

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at span
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/avatar/dist/chunk-XBMXQVV7.mjs:17:369)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:23:115)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:15:108)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:21:13)
    at Dropdown (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:17:13)
    at div
    at div
    at UserButton (webpack-internal:///(ssr)/./components/auth/user-button.tsx:22:87)
    at li
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-MG5LCNUN.mjs:19:13)
    at ul
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:18:13)
    at header
    at nav
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-CMNN5TJ7.mjs:25:13)
    at Navbar (webpack-internal:///(ssr)/./components/header/navbar.tsx:39:87)
    at Lazy
    at div
    at f (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.module.js:8:348)
    at $ea8dcbcb9ea1b556$export$323e4fc2fa4753fb (webpack-internal:///(ssr)/./node_modules/@react-aria/utils/dist/import.mjs:508:21)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/import.mjs:1069:54)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/import.mjs:1036:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (webpack-internal:///(ssr)/./node_modules/@react-aria/i18n/dist/real-module.mjs:170:19)
    at NextUIProvider (webpack-internal:///(ssr)/./node_modules/@nextui-org/system/dist/chunk-HRMF5D3P.mjs:15:3)
    at NextProvider (webpack-internal:///(ssr)/./providers/nextuiprovider.tsx:17:25)
    at Lazy
    at body
    at html
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react.js:232:13)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:308:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:177:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:159:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:517:13)
    at Lazy
    at Lazy
    at rw (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:15737)
    at rw (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:15737)
    at ServerInsertedHTMLProvider (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:21384)
 ✓ Compiled in 1411ms (1350 modules)

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Run the app locally on pc.

### Expected behavior

No warnings.

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Edge

### LINKED ISSUE #2593: Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
### NextUI Version

2.2.10

### Describe the bug

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at ap (/Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+popover@2.1.15_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18_gkrcnwyrxol7ft6cikewwoddve/node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:25:113)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+dropdown@2.1.17_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@1_jcm6p4e3f63y6chdc3cz24sr6m/node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:17:106)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+popover@2.1.15_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18_gkrcnwyrxol7ft6cikewwoddve/node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:23:11)
    at Dropdown (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+dropdown@2.1.17_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@1_jcm6p4e3f63y6chdc3cz24sr6m/node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:19:11)
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+navbar@2.0.27_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18._aa53oj6mpjpnf4cduu4q4wgjqm/node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:20:11)
    at header
    at nav
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+navbar@2.0.27_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18._aa53oj6mpjpnf4cduu4q4wgjqm/node_modules/@nextui-org/navbar/dist/chunk-CMNN5TJ7.mjs:27:11)
    at Lazy
    at div
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:298:11)
    at Router (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:154:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:99:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:128:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:426:13)
    at Lazy
    at Lazy
    at /Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:374733
    at /Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:374733
    at ServerInsertedHTMLProvider (/Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:23140)

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element. 

### Expected behavior

how to fix it.

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by wingkwong**
- Closes #2474
- Closes #2528
- Closes #2593

## 📝 Description

Currently if you create a Custom Trigger in Dropdown with elements which don't have `isDisabled` prop, e.g. `div`, `<User/>`, adding `isDisabled` would make React fail to recognize it on a DOM element. Hence, adding the `isDisabled` logic to cover this case. Also remove `isDisabled` prop for non NextUI button elements.

## ⛳️ Current behavior (updates)

Currently if you set `isDisabled` to dropdown, it won't make it disabled.

image

## 🚀 New behavior

With this fix, the dropdown is disabled.

image

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new property `isDropdownDisabled` for enhanced control over the disabled state of Popover triggers.
- **Enhancements**
	- Improved handling of custom triggers and DOM elements within Popover components, including disabled state management.
	- Added a utility function to identify NextUI components, enhancing component recognition capabilities.

### CODE REVIEW

File: packages/components/popover/src/popover-trigger.tsx [hunk 1]
```diff
@@ -38,11 +38,22 @@ const PopoverTrigger = forwardRef<"button", PopoverTriggerProps>((props, _) => {
 
   const {buttonProps} = useAriaButton({onPress}, triggerRef);
 
+  let restProps = rest;
```
Comment (jrgarciadev) [inline packages/components/popover/src/popover-trigger.tsx:41]:
```suggestion
  const {onPress, ...restProps} = useMemo(() => {
    return getTriggerProps(mergeProps(otherProps, child.props), child.ref);
  }, [getTriggerProps, child.props, otherProps, child.ref]);
  // validates if contains a NextUI Button as a child
  const [, triggerChildren] = pickChildren(children, Button);

  const {buttonProps} = useAriaButton({onPress}, triggerRef);
```

File: packages/components/popover/src/popover-trigger.tsx [hunk 2]
```diff
@@ -38,11 +38,22 @@ const PopoverTrigger = forwardRef<"button", PopoverTriggerProps>((props, _) => {
...
   const hasNextUIButton = useMemo<boolean>(() => {
     return triggerChildren?.[0] !== undefined;
   }, [triggerChildren]);
 
-  return cloneElement(child, mergeProps(rest, hasNextUIButton ? {onPress} : buttonProps));
+  if (restProps?.isDisabled) {
+    // if `child` doesn't have `isDisabled` prop, e.g. custom trigger (div), NextUI User component
+    // adding `isDisabled` would make React fail to recognize it on a DOM element
+    // hence, adding the `isDisabled` logic to cover this case
+    restProps.className = cn(restProps.className, "opacity-disabled pointer-events-none");
```
Comment (jrgarciadev) [inline packages/components/popover/src/popover-trigger.tsx:51]: @wingkwong we can't use tailwindcss classes outside the `theme` package, this is because users load the tailwindcss styles only from the `theme` package https://nextui.org/docs/guide/installation#tailwind-css-setup

I think we could manage this scenario directly in the `getTriggerProps`

**Comment by jrgarciadev** [comment]
@wingkwong could you please add some tests to avoid this happening in the future?

File: packages/components/popover/src/use-popover.ts [hunk 3]
```diff
@@ -244,7 +244,12 @@ export function usePopover(originalProps: UsePopoverProps) {
         "aria-haspopup": "dialog",
         ...mergeProps(triggerProps, props),
         onPress,
-        className: slots.trigger({class: clsx(classNames?.trigger, props.className)}),
+        className: slots.trigger({
+          class: clsx(classNames?.trigger, props.className),
+          // apply isDisabled class names to make the trigger child disabled
+          // e.g. for elements like div or NextUI elements that don't have `isDisabled` prop
+          isDropdownDisabled: !!props?.isDisabled,
```
[the remark this answers is not in the document]
Comment (wingkwong) [reply packages/components/popover/src/use-popover.ts:251]: confirmed it was introduced in [v0.1.14](https://github.com/nextui-org/tailwind-variants/releases/tag/v0.1.14).

**Review by jrgarciadev — APPROVED** [review]
