### PR TITLE
fix(theme): removed pseudo cancel btn from input

### LINKED ISSUE #3907: [BUG] - Two(instead of one) clear icons pop up from `<Input />`
### NextUI Version

2.4.8

### Describe the bug

Two clear icons pop up.

스크린샷 2024-10-17 오전 9 53 38

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

```tsx
import { Input } from '@nextui-org/react'

<Input isClearable type="search" variant="underlined" />
```

### Expected behavior

I expected only a single clear icon appear.

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by sanuj21**
Closes #3907 

## 📝 Description
Pseudo Cancel Button used to come with input element in chrome unintentionally when the input type is search.

## ⛳️ Current behavior (updates)
Pseudo Cancel Button comes with input element in chrome when the type is search.
Screenshot from 2024-10-18 04-38-40

## 🚀 New behavior
Removed the cancel button which was unintentional.
Screenshot from 2024-10-18 04-41-06

## 💣 Is this a breaking change (Yes/No):
No

## Summary by CodeRabbit

- **New Features**
	- Removed the pseudo cancel button from input components for a cleaner appearance.

- **Bug Fixes**
	- Addressed the issue of the pseudo cancel button display in input components as noted in issue #3907.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
it's still here. please double check.

```
<Input isClearable type="search" variant="underlined" />
```

image

**Comment by sanuj21** [comment]
@wingkwong I checked it again its working while running with storybook.
However, I tried to replicate the same scenerio using a test project and than linking to the nextui using pnpm link.
But while linking, it creates a symlink of folder nextui in node_modules, but we import from @nextui-org right.
Is it an alias issue, or its a build folder ? 
Or is there any specific way to setup this ?

**Comment by wingkwong** [comment]
I also tested in storybook only. Which browser were you testing in?

File: packages/core/theme/src/components/input.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ const input = tv({
       "data-[has-end-content=true]:pe-1.5",
       "file:cursor-pointer file:bg-transparent file:border-0",
       "autofill:bg-transparent bg-clip-text",
+      "input-search-cancel-button-none",
```
Comment (wingkwong) [inline packages/core/theme/src/components/input.ts:49]: i think we should hide it only when isClearable is true. Otherwise, it will break the existing behaviour for the false case.

Comment (sanuj21) [reply packages/core/theme/src/components/input.ts:49]: But lets say, isClearable is false. Then it will still have a clear button in chrome(when the type is search), which shouldn't be the case right ?
Also I tested in chrome, did you build it ? Because the changes are not getting reflected without build.

Comment (wingkwong) [reply packages/core/theme/src/components/input.ts:49]: - if `isClearable` is `false` and `type=search`, then it should show webkit-search-cancel-button because we don't want to break the native behaviour. 
- if `isClearable` is `true` and `type=search`, then it should only show NextUI Close button (since it supports onClear handle) and hide webkit-search-cancel-button one.
- True. The theme package needs to be built.

**Review by wingkwong — APPROVED** [review]
