### PR TITLE
fix: remove conflicting transition utilities

### LINKED ISSUE #1502: [BUG] - The default `transition` of tailwindcss is overridden by the `nextui` plugin and has a higher priority.
### NextUI Version

2.1.5

### Describe the bug

This will prevent me from directly setting my own `transition` effect.

image

image

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Add the `nextui()` plugin to `tailwind.config.js`.

### Expected behavior

There should not be duplicate `transition`.

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by u3u**
Remove the default duplicate Transition utilities in TailwindCSS (they do not need to be redefined) to prevent users from customizing transition effects, such as `duration-300` being overridden by the higher priority of the NextUI Plugin and not working.

Removing these redundant transition effects will not cause existing component effects to fail because TailwindCSS already includes them. Please feel free to check the preview documentation page. We only need to set `DEFAULT_TRANSITION_DURATION` to the `DEFAULT` key in order to modify the default transition time.

See: https://tailwindcss.com/docs/transition-property

Closes #1502 

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **Bug Fixes**
	- Patched the theme package to resolve conflicts with transition utilities, enhancing CSS compatibility and addressing issue #1502.
	- Removed conflicting transition definitions affecting CSS classes.

### CODE REVIEW

File: packages/core/theme/src/utilities/transition.ts [hunk 1]
```diff
@@ -1,36 +1,36 @@
...
-  ".transition-all": {
-    "transition-property": "all",
-    "transition-timing-function": "ease",
-    "transition-duration": DEFAULT_TRANSITION_DURATION,
-  },
+  // ".transition-all": {
+  //   "transition-property": "all",
+  //   "transition-timing-function": "ease",
+  //   "transition-duration": DEFAULT_TRANSITION_DURATION,
+  // },
```
Comment (wingkwong) [inline packages/core/theme/src/utilities/transition.ts:11]: do we actually need to keep them as comments? or we can remove them to keep the code clean?

Comment (u3u) [reply packages/core/theme/src/utilities/transition.ts:11]: Okay, I also think it's unnecessary.

**Review by jrgarciadev — APPROVED** [review]
Thanks! @u3u

**Comment by eBinaaOM** [comment]
@u3u @jrgarciadev Hello guys, I am having this trouble and I am a beginner , how can I use the fix?
