### PR TITLE
fix(avatar): avoid passing `disableAnimation` prop to a DOM element

### LINKED ISSUE #3109: [BUG] - React does not recognize the `disableAnimation` prop on a DOM element.
### NextUI Version

2.4.0

### Describe the bug

React does not recognize the `disableAnimation` prop on a DOM element.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

create an avatar with image

### Expected behavior

no such error

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #3109

## 📝 Description

> Add a brief description

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved an issue in the avatar component to prevent passing the `disableAnimation` prop to a DOM element, ensuring better compatibility and performance.
  
- **Improvements**
  - Enhanced the avatar component with improved logic for filtering DOM properties based on the type of image component, leading to more robust and flexible behavior.

### CODE REVIEW

File: packages/components/avatar/src/use-avatar.ts [hunk 1]
```diff
@@ -196,14 +196,25 @@ export function useAvatar(originalProps: UseAvatarProps = {}) {
...
+      return {
+        ref: imgRef,
+        src: src,
+        ...(allowDisableAnimation && {disableAnimation}),
+        "data-loaded": dataAttr(isImgLoaded),
+        className: slots.img({class: classNames?.img}),
+        ...mergeProps(imgProps, props),
+      };
+    },
     [slots, isImgLoaded, imgProps, disableAnimation, src, imgRef],
```
Comment (jrgarciadev) [inline packages/components/avatar/src/use-avatar.ts:218]: @wingkwong please implement it in this way which is how we handle this scenario in other components

```
  const shouldFilterDOMProps = typeof ImgComponent === "string";
  
  ...
  
  return {
        ref: imgRef,
        src: src,
        filterDOMProps({disableAnimation}, {
          enabled: shouldFilterDOMProps,
        }),
        "data-loaded": dataAttr(isImgLoaded),
        className: slots.img({class: classNames?.img}),
        ...mergeProps(imgProps, props),
      };
  ...


```

**Review by jrgarciadev — CHANGES_REQUESTED** [review]

File: packages/components/avatar/src/use-avatar.ts [hunk 2]
```diff
@@ -199,12 +201,17 @@ export function useAvatar(originalProps: UseAvatarProps = {}) {
...
+      ...mergeProps(
+        imgProps,
+        props,
+        filterDOMProps({disableAnimation} as DOMAttributes<DOMElement>, {
+          enabled: shouldFilterDOMProps,
+        }),
+      ),
     }),
-    [slots, isImgLoaded, imgProps, disableAnimation, src, imgRef],
+    [slots, isImgLoaded, imgProps, disableAnimation, src, imgRef, filterDOMProps],
```
Comment (jrgarciadev) [inline packages/components/avatar/src/use-avatar.ts:214]:
```suggestion
    [slots, isImgLoaded, imgProps, disableAnimation, src, imgRef, filterDOMProps],
```

@wingkwong as `filterDOMProps` is a function so it will cause the useCallback act as a normal function

**Review by jrgarciadev — APPROVED** [review]

**Comment by AmazingTurtle** [comment]
I am on 2.4.2 and the error persists. Anyone else?

**Comment by wingkwong** [comment]
@AmazingTurtle Sorry about that. I can confirm that there is an extra `disableAnimation` introduced during resolving the merge conflict. I've made another PR [here](https://github.com/nextui-org/nextui/pull/3260).

**Comment by paperdiamond** [comment]
Thank you! Yes I'm experiencing it on 2.4.2 as well. Hope the new PR gets merged soon =)

**Comment by wingkwong** [comment]
@AmazingTurtle @paperdiamond The PR has been merged. You guys can use the canary version `0.0.0-canary-20240616172522` as a temp fix at the moment.

**Comment by paperdiamond** [comment]
Thank you @wingkwong that did resolve the issue =)
