### PR TITLE
fix(select): label placement discrepancy in Select

### LINKED ISSUE #3841: [BUG] - Label placement - "outside" conflicts with Multiline property in Select element
### NextUI Version

2.4.8

### Describe the bug

Label position in `Select` element depends on properties: `labelPlacement="outside"` and `isMultiline={true}`.
With `isMultiline={true}`, the label is displayed inside select border.

Code:
```
<Select
    labelPlacement={"outside"}
    label="User Properties"
    placeholder="Select properties"
    className="w-full"
    variant="bordered"
    selectedKeys={selection}
    items={properties}
    isMultiline={true}
>
    {properties.map((prop) => (
        <SelectItem key={prop} value={prop}>
            {prop}
        </SelectItem>
    ))}
</Select>
```
Visualization:
{A192378E-3109-424F-946D-5DAFA995D999}

Other way - without multiline
Code:
```
<Select
    labelPlacement={"outside"}
    label="User Properties"
    placeholder="Select properties"
    className="w-full"
    variant="bordered"
    selectedKeys={selection}
    items={properties}
    isMultiline={false}
>
    {properties.map((prop) => (
        <SelectItem key={prop} value={prop}>
            {prop}
        </SelectItem>
    ))}
</Select>
```

{4CD0C7F0-1E86-450D-8DB0-471937B00975}

Also, This issue can be found in NextUI documentation:
{93606098-AA3E-4F3D-8BA7-0DBFCA4ABA19}

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Import Select, SelectItem components.
2. Create `Select` element
3. Set `labelPlacement="outside"` property to the item.
4. Set `isMultiline={true}` property to the item.

### Expected behavior

Label placement should not depend by `isMultiline` value (the label should be outside)

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Chrome

### PR DESCRIPTION
**Pull request by macci001**
Closes #3841 

#### 📝 Description

The PR makes changes to use the label placement in select according to the shouldLabelBeOutside rather than isOutsideLeft. This resolves the label placement issues in case of multiline.

#### ⛳️ Current behavior (updates)

Label is not placed outside when the multiline is true.
Eg. for the below code sample:
```
<Select
    labelPlacement={"outside"}
    label="User Properties"
    placeholder="Select properties"
    className="w-full"
    variant="bordered"
    selectedKeys={selection}
    items={properties}
    isMultiline={true}
>
    {properties.map((prop) => (
        <SelectItem key={prop} value={prop}>
            {prop}
        </SelectItem>
    ))}
</Select>
```
The output is follows:
Screenshot 2024-10-07 at 12 21 54 PM

#### 🚀 New behavior

After the changes in the PR, the same code above appears as follows:
Screenshot 2024-10-07 at 12 28 12 PM

### Additional Details
There shouldn't be any side effect to this as it targets only the following variant: 
```
{
      labelPlacement: "outside",
      isMultiline: true,
      class: {
        label: "pb-1.5",
      },
    },
```
Again, just for sanity check. Some tests are made as follows:
* When labelPlacement is outside-left and multiline is true:
Screenshot 2024-10-07 at 12 31 14 PM

* When labelPlacement is inside multiline is true:
Screenshot 2024-10-07 at 12 31 37 PM

* When labelPlacement is outside multiline is false:
Screenshot 2024-10-07 at 12 37 16 PM

* When labelPlacement is outside-left multiline is false:
Screenshot 2024-10-07 at 12 37 27 PM

* When labelPlacement is inside multiline is false:
Screenshot 2024-10-07 at 12 37 03 PM

## Summary by CodeRabbit

- **New Features**
	- Improved label placement logic in the select component for better handling of multiline scenarios.
  
- **Bug Fixes**
	- Resolved issues related to label placement, enhancing usability and accessibility.

- **Documentation**
	- Updated property name from `isOutsideLeft` to `shouldLabelBeOutside` for clarity in the select component's props interface.

### CODE REVIEW

File: packages/components/select/src/select.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ function Select<T extends object>(props: Props<T>, ref: ForwardedRef<HTMLSelectE
     endContent,
     placeholder,
     renderValue,
-    isOutsideLeft,
+    shouldLabelBeOutside,
```
[the remark this answers is not in the document]
Comment (macci001) [reply packages/components/select/src/select.tsx:32]: Tests added

File: packages/components/select/__tests__/select.test.tsx [hunk 2]
```diff
@@ -720,6 +720,63 @@ describe("Select", () => {
       expect(onChange).toBeCalledTimes(1);
     });
   });
+
+  it("should place the label outside when labelPlacement is outside", async () => {
```
Comment (wingkwong) [inline packages/components/select/__tests__/select.test.tsx:724]: `async` seems not require

File: packages/components/select/__tests__/select.test.tsx [hunk 3]
```diff
@@ -720,6 +720,63 @@ describe("Select", () => {
...
+    );
+
+    const base = document.querySelector("[data-slot=base]");
+    const trigger = document.querySelector("[data-slot=trigger]");
+
+    expect(base).toHaveTextContent(labelContent);
+    expect(trigger).not.toHaveTextContent(labelContent);
+  });
+
+  it("should place the label inside when labelPlacement prop is not passed", async () => {
```
Comment (wingkwong) [inline packages/components/select/__tests__/select.test.tsx:754]: `async` seems not require

File: .changeset/dull-bags-divide.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@nextui-org/select": patch
+---
+
+The PR makes changes to use the label placement in select according to the shouldLabelBeOutside rather than isOutsideLeft. This resolves the label placement issues in case of multiline.(fixes issue: #3841)
```
Comment (wingkwong) [inline .changeset/dull-bags-divide.md:5]: - make it shorter
- ended with `(#3841)`

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: .changeset/dull-bags-divide.md (hunk 4 above)
Comment (macci001) [reply .changeset/dull-bags-divide.md]: Done in: 57bfd32

File: packages/components/select/__tests__/select.test.tsx (hunk 3 above)
Comment (macci001) [reply packages/components/select/__tests__/select.test.tsx]: Done in: 57bfd32

File: packages/components/select/__tests__/select.test.tsx (hunk 2 above)
Comment (macci001) [reply packages/components/select/__tests__/select.test.tsx]: Done in:  57bfd32

**Review by wingkwong — APPROVED** [review]
