### PR TITLE
fix(hooks): handle numeric selectedKeys in Select 

### LINKED ISSUE #2587: [BUG] - Select controlled mode not support number key
### NextUI Version

2.2.10

### Your Example Website or App

[https://stackblitz.com/\~/github.com/Zeiion/react-nextui](https://stackblitz.com/\~/github.com/Zeiion/react-nextui)

### Steps to Reproduce the Bug or Issue

1. npm install & npm run dev
2. the first select is not default selected

### Expected behavior

\`\` is expect to support React.Key (string | number), so the first select should be default selected and works well when selecting new items

### Screenshots or Videos

CleanShot 2024-03-26 at 16 49 12

### Operating System Version

macOS

### Browser

Chrome

### Describe the bug

the `selectedKeys` props for the \`\` is not working when keys are numeric
but when i parse them into strings, it works.

The problem seems to appear in `packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts`

```typescript
const {
    collection,
    disabledKeys,
    selectionManager,
    selectionManager: {setSelectedKeys, selectedKeys, selectionMode},
  } = useListState(props);
```

when call `collection.getItem(1)`, it gets `undefined`

sb test to reproduce the bug can be add as

```typescript
const ControlledNumberTemplate = ({color, variant, ...args}: SelectProps<User>) => {
  const [value, setValue] = React.useState<Selection>(new Set([1]));

  const handleSelectionChange = (e: ChangeEvent<HTMLSelectElement>) => {
    setValue(new Set([Number(e.target.value)]));
  };

  return (
    <div className="flex flex-col w-full max-w-xs gap-2">
      <Select
        className="max-w-xs mt-8"
        color={color}
        items={usersData}
        label="Assigned to"
        selectedKeys={value}
        variant={variant}
        onChange={handleSelectionChange}
        {...args}
      >
        {(item) => (
          <SelectItem key={item.id} textValue={item.name}>
            <div className="flex items-center gap-2">
              <Avatar alt={item.name} className="flex-shrink-0" size="sm" src={item.avatar} />
              <div className="flex flex-col">
                <span className="text-small">{item.name}</span>
                <span className="text-tiny text-default-400">{item.email}</span>
              </div>
            </div>
          </SelectItem>
        )}
      </Select>
      <p className="text-default-500">Selected: {value}</p>
    </div>
  );
};
```

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #2587

## 📝 Description

In collection, the key of the map is always string no matter the inputted key is numeric or string. Therefore, handle such case when we get the item from the collection.

## ⛳️ Current behavior (updates)

image

## 🚀 New behavior

image

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **Bug Fixes**
    - Improved handling of numeric keys in the multi-select component to ensure consistent behavior.

### CODE REVIEW

File: packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export function useMultiSelectListState<T extends object>(
     if (selectedKeys.size !== 0) {
       return Array.from(selectedKeys)
         .filter(Boolean)
-        .filter((key) => !collection.getItem(key));
+        .filter((key) => !collection.getItem(key + ""));
```
Comment (jrgarciadev) [inline packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts:32]:
```suggestion
        .filter((key) => !collection.getItem(`${key}`));
```

File: packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts [hunk 2]
```diff
@@ -39,7 +39,7 @@ export function useMultiSelectListState<T extends object>(
     selectedKeys.size !== 0
       ? Array.from(selectedKeys)
           .map((key) => {
-            return collection.getItem(key);
+            return collection.getItem(key + "");
```
Comment (jrgarciadev) [inline packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts:42]:
```suggestion
            return collection.getItem(`${key}`);
```

**Review by jrgarciadev — APPROVED** [review]
